name: 'Huge docker builder with privilege'
description: 'Free 80GB on github runner and then build & push to dockerhub'
branding:
  color: 'red'
inputs:
  docker-username:
    description: ''
    required: true
  
  docker-password:
    description: ''
    required: true
  
  step-image-name:
    description: ''
    required: true
  
  use-image-name:
    description: ''
    required: true
  
  run-command:
    description: ''
    required: true
  
  before-run:
    description: ''
    required: false
    default: ''
  
  after-run:
    description: ''
    required: false
    default: ''
  


  
runs:
  using: "composite"
  steps:
    - name: Check if image exist on duckerhub
      id: check-image
      shell: bash
      run: |
          (docker manifest inspect ${{ inputs.step-image-name }} > /dev/null; echo "::set-output name=IMAGE_EXIST::$?") || echo true

    - name: Free up & login to docker
      if: ${{ false == steps.check-image.outputs.IMAGE_EXIST == 0 }}
      shell: bash
      run: |
          set -euo pipefail
          docker login -u ${{ inputs.docker-username }} -p ${{ inputs.docker-password }}
          
          
          BUILD_MOUNT_PATH="${GITHUB_WORKSPACE}"
          sudo rm -rf "/usr/local/"
          echo "Please wait 3 minutes"
          sudo rm -rf "/usr/share/"
          echo "Please wait 2 minutes"
          sudo rm -rf "/opt/"
          echo "Please wait 1 minutes"
          
          VG_NAME=buildvg
          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          # create loop pv image on root fs # around 69GB
          ROOT_RESERVE_KB=$(expr 256 \* 1024)
          ROOT_FREE_KB=$(df --block-size=1024 --output=avail / | tail -1)
          ROOT_LVM_SIZE_KB=$(expr $ROOT_FREE_KB - $ROOT_RESERVE_KB)
          ROOT_LVM_SIZE_BYTES=$(expr $ROOT_LVM_SIZE_KB \* 1024)
          sudo touch "/pv.img" && sudo fallocate -z -l "${ROOT_LVM_SIZE_BYTES}" "/pv.img"
          export ROOT_LOOP_DEV=$(sudo losetup --find --show "/pv.img")
          sudo pvcreate -f "${ROOT_LOOP_DEV}"
          # create pv on temp disk
          TMP_RESERVE_KB=$(expr 128 \* 1024)
          TMP_FREE_KB=$(df --block-size=1024 --output=avail /mnt | tail -1)
          TMP_LVM_SIZE_KB=$(expr $TMP_FREE_KB - $TMP_RESERVE_KB)
          TMP_LVM_SIZE_BYTES=$(expr $TMP_LVM_SIZE_KB \* 1024)
          sudo touch "/mnt/tmp-pv.img" && sudo fallocate -z -l "${TMP_LVM_SIZE_BYTES}" "/mnt/tmp-pv.img"
          export TMP_LOOP_DEV=$(sudo losetup --find --show "/mnt/tmp-pv.img")
          sudo pvcreate -f "${TMP_LOOP_DEV}"
          # create volume group from these pvs
          sudo vgcreate "${VG_NAME}" "${TMP_LOOP_DEV}" "${ROOT_LOOP_DEV}"
          # create and activate swap
          sudo lvcreate -L "4096M" -n swap "${VG_NAME}"
          sudo mkswap "/dev/mapper/${VG_NAME}-swap"
          sudo swapon "/dev/mapper/${VG_NAME}-swap"
          # create and mount build volume
          sudo lvcreate -l 100%FREE -n buildlv "${VG_NAME}"
          sudo mkfs.ext4 -Enodiscard -m0 "/dev/mapper/${VG_NAME}-buildlv"
          sudo mount "/dev/mapper/${VG_NAME}-buildlv" "${BUILD_MOUNT_PATH}"
          sudo chown -R runner "${BUILD_MOUNT_PATH}"
          sudo chgrp -R runner "${BUILD_MOUNT_PATH}"
          
          echo $'{\n  "graph": "'$GITHUB_WORKSPACE'" }' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          sleep 5
          
          ${{ inputs.before-run }}
          cd
          cat >> tmp_7dj29fh467dslja3er309dmn10cvxkadsf3.sh << TEMPSCRIPTFILEEOF
          ${{ inputs.run-command }}
          rm /home/tmp_7dj29fh467dslja3er309dmn10cvxkadsf3.sh 
          TEMPSCRIPTFILEEOF

          docker run --interactive --tty --detach --privileged --name tbb ${{ inputs.use-image-name }}
          docker cp tmp_7dj29fh467dslja3er309dmn10cvxkadsf3.sh tbb:/home/
          docker image rm --force ${{ inputs.use-image-name }}
          docker exec tbb bash -c "cd /home && chmod +x tmp_7dj29fh467dslja3er309dmn10cvxkadsf3.sh && ./tmp_7dj29fh467dslja3er309dmn10cvxkadsf3.sh "
          docker commit tbb ${{ inputs.step-image-name }}
          docker login -u ${{ inputs.docker-username }} -p ${{ inputs.docker-password }}
          docker push ${{ inputs.step-image-name }}
          ${{ inputs.after-run }}

#    - name: Final report
#      shell: bash
#      run: |
#        echo "done"
#
