name: 'Huge docker builder with privilege'
description: 'Free 80GB on github runner and then build & push to dockerhub'
branding:
  color: 'red'
inputs:
  docker-username:
    description: ''
    required: true
  
  docker-password:
    description: ''
    required: true
  
  step-image-name:
    description: ''
    required: true
  
  use-image-name:
    description: ''
    required: true
  
  run-command:
    description: ''
    required: true
    


  
runs:
  using: "composite"
  steps:
    - name: Free up & login to docker
      shell: bash
      run: |
          set -euo pipefail
          (docker manifest inspect ${{ inputs.step-image-name }} > /dev/null; if [ $? == 0 ]; then echo "Already exist on DockerHub "; exit 0; fi) || echo true
          docker login -u ${{ inputs.docker-username }} -p ${{ inputs.docker-password }}
          
          
          BUILD_MOUNT_PATH="${GITHUB_WORKSPACE}"
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
          
          VG_NAME=buildvg
          # github runners have an active swap file in /mnt/swapfile
          # we want to reuse the temp disk, so first unmount swap and clean the temp disk
          echo "Unmounting and removing swap file."
          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          echo "Creating LVM Volume."
          echo "  Creating LVM PV on root fs."
          # create loop pv image on root fs # around 69GB
          ROOT_RESERVE_KB=$(expr 69000 \* 1024)
          ROOT_FREE_KB=$(df --block-size=1024 --output=avail / | tail -1)
          ROOT_LVM_SIZE_KB=$(expr $ROOT_FREE_KB - $ROOT_RESERVE_KB)
          ROOT_LVM_SIZE_BYTES=$(expr $ROOT_LVM_SIZE_KB \* 1024)
          sudo touch "/pv.img" && sudo fallocate -z -l "${ROOT_LVM_SIZE_BYTES}" "/pv.img"
          export ROOT_LOOP_DEV=$(sudo losetup --find --show "/pv.img")
          sudo pvcreate -f "${ROOT_LOOP_DEV}"
          # create pv on temp disk
          echo "  Creating LVM PV on temp fs."
          TMP_RESERVE_KB=$(expr 8 \* 1024)
          TMP_FREE_KB=$(df --block-size=1024 --output=avail /mnt | tail -1)
          TMP_LVM_SIZE_KB=$(expr $TMP_FREE_KB - $TMP_RESERVE_KB)
          TMP_LVM_SIZE_BYTES=$(expr $TMP_LVM_SIZE_KB \* 1024)
          sudo touch "/mnt/tmp-pv.img" && sudo fallocate -z -l "${TMP_LVM_SIZE_BYTES}" "/mnt/tmp-pv.img"
          export TMP_LOOP_DEV=$(sudo losetup --find --show "/mnt/tmp-pv.img")
          sudo pvcreate -f "${TMP_LOOP_DEV}"
          # create volume group from these pvs
          sudo vgcreate "${VG_NAME}" "${TMP_LOOP_DEV}" "${ROOT_LOOP_DEV}"
          echo "Recreating swap"
          # create and activate swap
          sudo lvcreate -L "12228M" -n swap "${VG_NAME}"
          sudo mkswap "/dev/mapper/${VG_NAME}-swap"
          sudo swapon "/dev/mapper/${VG_NAME}-swap"
          echo "Creating build volume"
          # create and mount build volume
          sudo lvcreate -l 100%FREE -n buildlv "${VG_NAME}"
          sudo mkfs.ext4 -Enodiscard -m0 "/dev/mapper/${VG_NAME}-buildlv"
          sudo mount "/dev/mapper/${VG_NAME}-buildlv" "${BUILD_MOUNT_PATH}"
          sudo chown -R runner "${BUILD_MOUNT_PATH}"
          sudo chgrp -R runner "${BUILD_MOUNT_PATH}"
          
          cd /home
          cat >> bscript.sh << EOF
          ${{ inputs.run-command }}
          rm /home/bscript.sh 
          EOF
          
          docker run --interactive --tty --detach --privileged --name tbb ${{ inputs.use-image-name }}
          docker cp bscript.sh tbb:/home/
          docker exec tbb bash -c "cd /home && chmod +x bscript.sh && ./bscript.sh "
          docker commit tbb ${{ inputs.step-image-name }}
          docker push ${{ inputs.step-image-name }}
#    - name: Final report
#      shell: bash
#      run: |
#        echo "done"
#
